# Generated by Django 5.2.8 on 2025-12-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='voting',
            name='option1',
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name='voting',
            name='option2',
            field=models.CharField(max_length=24),
        ),
    ]
