# Generated by Django 6.0 on 2026-01-16 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='taken_down',
            field=models.BooleanField(default=False),
        ),
    ]
