# Generated by Django 5.2.8 on 2026-01-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_voting_taken_down'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
