# Generated by Django 5.2.8 on 2025-12-25 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_voting_description_alter_voting_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voting',
            name='option1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='voting',
            name='option2',
            field=models.CharField(max_length=20),
        ),
    ]
