# Generated by Django 6.0 on 2025-12-27 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_voting_name_alter_voting_option1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
