# Generated by Django 6.0 on 2026-01-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_theme',
            field=models.CharField(default='dark'),
        ),
    ]
