# Generated by Django 6.0 on 2026-01-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_voting_date_closed_alter_voting_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voting',
            name='description',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='voting',
            name='name',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='voting',
            name='option1',
            field=models.CharField(max_length=48),
        ),
        migrations.AlterField(
            model_name='voting',
            name='option2',
            field=models.CharField(max_length=48),
        ),
    ]
