# Generated by Django 6.0 on 2026-01-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_voting_description_alter_voting_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voting',
            name='option1',
        ),
        migrations.RemoveField(
            model_name='voting',
            name='option2',
        ),
        migrations.AddField(
            model_name='voting',
            name='options',
            field=models.JSONField(default=[]),
        ),
    ]
