# Generated by Django 6.0 on 2026-01-31 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_voting_can_view_results_alter_vote_voting'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='description_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
