# Generated by Django 6.0 on 2026-01-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_voting_option1_remove_voting_option2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voting',
            name='multichoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voting',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
